---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
spec:
  limits:
    - type: Container
      default:
        cpu:    1.0
        memory: 1Gi
      defaultRequest:
        cpu:    0.25
        memory: 256Mi
