---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine 
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.25
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer # This'll work if you set up an LB Service -- k3s comes with one, for example
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 1080 # Need to change especially if using k3s' ingress controller, where you can't map 80 from the host
      targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  # behavior:
  #   scaleUp:
  #     stabilizationWindowSeconds: 0
  #     policies:
  #       - type: Percent
  #         value: 100
  #         periodSeconds: 15
  #       - type: Pods
  #         value: 4
  #         periodSeconds: 15
  #   scaleDown:
  #     stabilizationWindowSeconds: 30
  #     policies:
  #       - type: Percent
  #         value: 100
  #         periodSeconds: 15
  #     selectPolicy: Max
